#!/usr/bin/env python

import sys
from mako.template import Template

def main():
    if len(sys.argv) != 3:
        print "usage: vpp file.t file.v"
        sys.exit(0)

    temp = sys.argv[1]
    file = sys.argv[2]

    temp = Template(open(temp).read())

    file = open(file, 'w')

    file.write(temp.render())

if __name__ == "__main__":
    main()
