#!/usr/bin/env python
import os, glob
from os.path import join, exists
from fabricate import main, autoclean, run

BUILD = 'build'
GOLD = 'gold'

tests = glob.glob('*.py')

def build():
    for test in tests:
        base, suffix = test.split('.')
        compile(base)

def compile(base):
    run('python',base+'.py', join(BUILD,base))

def clean():
    autoclean()

main()
